### PR TITLE
feat: add `allowChaiExclude` option

### PR DESCRIPTION
**Pull request by brettz9**
feat: add `allowChaiExclude` option to support https://github.com/mesaugat/chai-exclude

### CODE REVIEW

**Review by gavinaiken — COMMENTED** [review]
Thanks for the PR. 👍

**Comment by gavinaiken** [comment]
Merged this and the deps bump, updated the README and published as version `2.1.0`

**Comment by brettz9** [comment]
Great, thanks a lot! And, sorry I forgot to update the README. I didn't see any commit from you updating it. Would you like one?

**Comment by gavinaiken** [comment]
I forgot to push to github! Just done so. https://github.com/gavinaiken/eslint-plugin-chai-expect-keywords/commit/8b21ae312b4c25de0524b1b99a0e3b85c254653d

**Pull request merged**
